# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:23
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_auto_20160720_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.AddField(
            model_name='account',
            name='asset_limit',
            field=models.IntegerField(default=10, help_text='Give 0 for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='details',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(1, 'Monthly'), (2, 'Annually')], default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(null=True, upload_to='clients'),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
