# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160721_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
