# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160721_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
    ]
