# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160723_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], default='Monthly', max_length=64),
        ),
        migrations.AlterField(
            model_name='header',
            name='page',
            field=models.CharField(choices=[('Index', 'Index'), ('Pricing', 'Pricing'), ('Clients', 'Clients'), ('Contact', 'Contact'), ('About', 'About')], default='Index', max_length=64, unique=True),
        ),
    ]
