# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('web', '0013_auto_20160723_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=64, null=True)),
                ('company', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('zip_or_postal', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account',
        ),
        migrations.AddField(
            model_name='customer',
            name='apps',
            field=models.ManyToManyField(to='dashboard.Application'),
        ),
        migrations.AddField(
            model_name='customer',
            name='assets',
            field=models.ManyToManyField(to='dashboard.Asset'),
        ),
        migrations.AddField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(to='dashboard.DashUser'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually'), ('Free', 'Free')], default='Monthly', max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Payment'),
        ),
    ]
