# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20160728_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='apps',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Application'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assets',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Asset'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.DashUser'),
        ),
    ]
