# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20160730_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.AddField(
            model_name='customer',
            name='asset_limit',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='details',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually'), ('Free', 'Free')], default='Monthly', max_length=64),
        ),
    ]
