# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20160730_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
