# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20160730_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
