# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160817_1459'),
        ('web', '0020_auto_20160811_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assets',
            field=models.ManyToManyField(blank=True, to='dashboard.Asset'),
        ),
        migrations.AddField(
            model_name='customer',
            name='companies',
            field=models.ManyToManyField(blank=True, to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dashusers',
            field=models.ManyToManyField(blank=True, to='dashboard.DashUser'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hardwares',
            field=models.ManyToManyField(blank=True, to='dashboard.Hardware'),
        ),
        migrations.AddField(
            model_name='customer',
            name='locations',
            field=models.ManyToManyField(blank=True, to='dashboard.Location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, to='dashboard.Manufacturer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='softwares',
            field=models.ManyToManyField(blank=True, to='dashboard.Software'),
        ),
        migrations.AddField(
            model_name='customer',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='dashboard.Supplier'),
        ),
    ]
