# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20160819_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
    ]
