# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_settings_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='image1',
            field=models.ImageField(null=True, upload_to='features'),
        ),
        migrations.AddField(
            model_name='features',
            name='image1_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='image2',
            field=models.ImageField(null=True, upload_to='features'),
        ),
        migrations.AddField(
            model_name='features',
            name='image2_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='image3',
            field=models.ImageField(null=True, upload_to='features'),
        ),
        migrations.AddField(
            model_name='features',
            name='image3_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
