# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20160821_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('social_facebook_link', models.CharField(blank=True, max_length=255, null=True)),
                ('social_twitter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('footer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Demo',
        ),
        migrations.DeleteModel(
            name='Demos',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
