# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20160824_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='image1_text',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='image2_text',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='image3_text',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='maintenance_message',
        ),
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='text_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
