# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20160824_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color_code',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
