# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_account_price_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
