# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20160824_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
