# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20160928_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
    ]
