# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AddField(
            model_name='asset',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Application'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_type',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='localiton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory_type',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='order_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='platform',
            field=models.CharField(choices=[('Physical', 'Physical')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='role',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hardware'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Status'),
        ),
    ]
