# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160811_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Physical', 'Physical')], max_length=64, null=True),
        ),
    ]
