# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160812_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='localiton',
            new_name='location',
        ),
    ]
