# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20160814_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
        migrations.AddField(
            model_name='software',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='licensed_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='software',
            name='licensed_to_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='order_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='reassignable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='software',
            name='seats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='serial',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier'),
        ),
        migrations.AddField(
            model_name='software',
            name='termination_date',
            field=models.DateField(null=True),
        ),
    ]
