# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20160815_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='postal_code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dashuser',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
