# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160815_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Ready to Deploy', 'Ready to Deploy')], max_length=64, null=True),
        ),
    ]
