# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160815_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dashuser',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='location',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='software',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='customer',
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk_type',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory_type',
            field=models.CharField(choices=[('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(choices=[('Physical', 'Physical')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Ready to Deploy', 'Ready to Deploy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Access Point', 'Access Point'), ('Chassis', 'Chassis'), ('Computer', 'Computer'), ('Switch', 'Switch'), ('Router', 'Router'), ('Firewall', 'Firewall'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Projector', 'Projector'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Mobile Phone', 'Mobile Phone'), ('Video Conference', 'Video Conference'), ('VoIP Gateway', 'VoIP Gateway'), ('VoIP Phone', 'VoIP Phone'), ('Monitor', 'Monitor'), ('KVM (Keyboard, Video, Mouse switch)', 'KVM (Keyboard, Video, Mouse switch)'), ('Load Balancer', 'Load Balancer'), ('SAN (Storage Area Network)', 'SAN (Storage Area Network)'), ('NAS (Network Attached Storage', 'NAS (Network Attached Storage)'), ('Tape Library', 'Tape Library'), ('UPS', 'UPS'), ('General Purpose', 'General Purpose'), ('Other Computer Device', 'Other Computer Device'), ('Other Network Device', 'Other Network Device'), ('Other Security Device', 'Other Security Device'), ('Other Storage Device', 'Other Storage Device'), ('Other Telecom Device', 'Other Telecom Device'), ('Other Device', 'Other Device')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_currency',
            field=models.CharField(choices=[('$', '$')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='licensed_to_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='serial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
