# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160817_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='country',
            field=models.CharField(blank=True, choices=[('Turkey', 'Turkey')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashuser',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
