# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20160817_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='is_os',
        ),
        migrations.AddField(
            model_name='software',
            name='is_os',
            field=models.BooleanField(default=True),
        ),
    ]
