# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20160817_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.DashUser'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk_type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(blank=True, choices=[('', 'Select Platform'), ('Physical', 'Physical'), ('Virtual', 'Virtual'), ('Azure', 'Azure'), ('Amazon Web Services', 'Amazon Web Services')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('Ready to Deploy', 'Ready to Deploy'), ('Unassign', 'Unassign')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(choices=[('', 'Select Category Type'), ('Asset', 'Asset'), ('Access Point', 'Access Point'), ('Chassis', 'Chassis'), ('Computer', 'Computer'), ('Switch', 'Switch'), ('Router', 'Router'), ('Firewall', 'Firewall'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Projector', 'Projector'), ('Phone', 'Phone'), ('Tablet', 'Tablet'), ('Mobile Phone', 'Mobile Phone'), ('Video Conference', 'Video Conference'), ('VoIP Gateway', 'VoIP Gateway'), ('VoIP Phone', 'VoIP Phone'), ('Monitor', 'Monitor'), ('KVM (Keyboard, Video, Mouse switch)', 'KVM (Keyboard, Video, Mouse switch)'), ('Load Balancer', 'Load Balancer'), ('SAN (Storage Area Network)', 'SAN (Storage Area Network)'), ('NAS (Network Attached Storage', 'NAS (Network Attached Storage)'), ('Tape Library', 'Tape Library'), ('UPS', 'UPS'), ('General Purpose', 'General Purpose'), ('Other Computer Device', 'Other Computer Device'), ('Other Network Device', 'Other Network Device'), ('Other Security Device', 'Other Security Device'), ('Other Storage Device', 'Other Storage Device'), ('Other Telecom Device', 'Other Telecom Device'), ('Other Device', 'Other Device')], max_length=255, null=True),
        ),
    ]
