# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20160817_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ManyToManyField(to='dashboard.DashUser'),
        ),
    ]
