# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20160817_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='application',
        ),
        migrations.AddField(
            model_name='asset',
            name='application',
            field=models.ManyToManyField(blank=True, related_name='software', to='dashboard.Software'),
        ),
    ]
