# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20160818_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=12),
        ),
        # migrations.AddField(
        #     model_name='asset',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='hardware',
            name='category',
            field=models.CharField(
                choices=[('', 'Select Category Type'), ('ASS', 'Asset'), ('ACP', 'Access Point'), ('CHS', 'Chassis'),
                         ('CMP', 'Computer'), ('SWT', 'Switch'), ('RTR', 'Router'), ('FRW', 'Firewall'),
                         ('PRT', 'Printer'), ('SCN', 'Scanner'), ('PRJ', 'Projector'), ('PHN', 'Phone'),
                         ('TBL', 'Tablet'), ('MPH', 'Mobile Phone'), ('VCF', 'Video Conference'),
                         ('VGW', 'VoIP Gateway'), ('VPH', 'VoIP Phone'), ('Monitor', 'Monitor'),
                         ('KVM', 'KVM (Keyboard, Video, Mouse switch)'), ('BLC', 'Load Balancer'),
                         ('SAN', 'SAN (Storage Area Network)'), ('NAS', 'NAS (Network Attached Storage)'),
                         ('TLB', 'Tape Library'), ('UPS', 'UPS'), ('GNR', 'General Purpose'),
                         ('OCP', 'Other Computer Device'), ('ONP', 'Other Network Device'),
                         ('OSD', 'Other Security Device'), ('OGD', 'Other Storage Device'),
                         ('OTD', 'Other Telecom Device'), ('OTH', 'Other Device')], max_length=255, null=True),
        ),
    ]
