# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_asset_fix_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='application',
            field=models.ManyToManyField(blank=True, related_name='software', to='dashboard.Software', verbose_name='Assigned Software'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=12, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.DashUser', verbose_name='User Assigned'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU Count'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cpu_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True, verbose_name='Cpu Speed'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True, verbose_name='Disk Size'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disk_type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True, verbose_name='Disk Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True, verbose_name='Memory Size'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('TB', 'TB'), ('GB', 'GB'), ('MB', 'MB')], max_length=255, null=True, verbose_name='Memory Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Hardware', verbose_name='Hardware Model'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='dashboard.Software', verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.CharField(blank=True, choices=[('', 'Select Platform'), ('Physical', 'Physical'), ('Virtual', 'Virtual'), ('Azure', 'Azure'), ('Amazon Web Services', 'Amazon Web Services')], max_length=255, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('Ready to Deploy', 'Ready to Deploy'), ('Unassign', 'Unassign')], max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Warranty'),
        ),
    ]
