# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20160819_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='company',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
