# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20160820_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('Turkey', 'Turkey')], max_length=255, null=True),
        ),
    ]
