# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20160823_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
