# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20160905_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Address'),
        ),
    ]
