# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20160908_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
